import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/config/fonts";
import { TopMenu } from "@/components/ui/top-menu/TopMenu";
import { Footer } from "@/components/ui/footer/Footer";
import { WhatsApp } from "@/components/buttons/WhatsApp";
import { ScrollButton } from "@/components/buttons/ScrollButton";


export const metadata: Metadata = {
  title: "MorenaMora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${inter.className} antialiased`}
      >
        <TopMenu/>
        {children}
        <ScrollButton/>        
        <WhatsApp/>
        <Footer/>
      </body>
    </html>
  );
}